### ISSUE TITLE
List packages to install

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#1]
README.md should list which packages should be installed

Definitely:
* tidyqpcr
* Biostrings
* bookdown
* tikzDevice
* latex2exp
* DECIPHER

**Comment by DimmestP** [comment]
Currently I just have the sessionInfo.txt file in the home folder of the git repo. Is that sufficient or should I look into alternatives?

**Comment by DimmestP** [comment]
Possibly look into Renv. Although this is a low priority

**Comment by DimmestP** [comment]
Used renv library to quickly load all required libraries and their versions for running the scripts.
