### ISSUE TITLE
What percentage of the variance is explained by codon usage and by motifs?

### ISSUE THREAD

**Issue by DimmestP** [DimmestP/chimera_project_manuscript#100]

**Comment by DimmestP** [comment]
Got myself into a muddle about how to calculate the variance explained by each component. Cheng et al 2017 do 10 fold cross validation on models with and without each component and compare mean variance explained. Alternatively, you can just calculate the ratio of sum of squares for each component and the total sum of square of the model (this is a biased estimate though) @ewallace

**Comment by ewallace** [comment]
I'm reopening this (hopefully briefly) because I'm confused about what the 3rd bit means:
"The total variance explained when each CRE is added to the linear model in sequence."

@DimmestP could you clarify what "in sequence" means? I think this is a quick fix. Related to #151.

**Comment by DimmestP** [comment]
Changed the table caption to read 

Variance explained was estimated in 3 different ways. The individual variance explained by a linear model containing each type of CRE on its own.  The drop in variance explained when one type of CRE is removed from the full model. The cumulative variance explained when each CRE is added to the linear model in sequence; starting with codon usage, then adding motifs and finally 3'UTR length.
