### ISSUE TITLE
Fix the "prime" in 3′UTR

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#103]
We need to fix the characters so that every mention of 3′UTR has the correct prime symbol, "′", [U+2032](https://www.compart.com/en/unicode/U+2032)

**Comment by DimmestP** [comment]
pdflatex doesn't support that symbol. I changed the latex engine to xelatex and knitr runs but the standard font doesn't show anything for that symbol. I've reverted to pdflatex and the single quotation mark.

**Comment by ewallace** [comment]
Ok - shall we just leave it like that and remember to correct to a real prime symbol in proof?

**Comment by ewallace** [comment]
I am deciding that this is something we just fix in proof and don't deal with now.
