### ISSUE TITLE
Add figure comparing fluorescence with RT-qPCR for motif constructs

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#110]
We had this figure, then it was taken out again, and we still need it (probably as supplementary).

What's happening and how are we we going to fix it?

**Comment by DimmestP** [comment]
Something like this? Similar to figure 1C

![RPS3_TSA1_PIR1_protein_and_RNA_plot](https://user-images.githubusercontent.com/37002508/115432925-d6a78500-a1fe-11eb-99d7-fbb86196d7ed.png)

**Comment by ewallace** [comment]
Wow! It's surprising how the substitutions in PIR1 increase the protein level while mildly decreasing the RNA level.

Yes, something like this. I suggest putting these side to side and making the PIR1 figure taller, so it can have a different "portrait" aspect ratio while maintaining `coord_equal`. Also it would be nice to get something to differentiate the points better, e.g. shape as well as colour?

If you tell me where this is on which branch, I could play around, or you could upgrade it?

**Comment by DimmestP** [comment]
Just pushed a protein_vs_RNA_motif_plot branch

**Comment by DimmestP** [comment]
The file is in [raw_data_analysis/code/raw_platereader_analysis/motif_context_dependence/RPS3_PIR1_TSA1_protein_vs_RNA_abund.Rmd](https://github.com/DimmestP/chimera_project_manuscript/tree/protein_vs_RNA_motif_plot/raw_data_analysis/code/raw_platereader_analysis/motif_context_dependence)

**Comment by ewallace** [comment]
I made these updates but we have to redo the plot from the ground up anyway (see below after image).
![image](https://user-images.githubusercontent.com/683603/116051865-f9a7be00-a670-11eb-9831-658560e37bbe.png)


This version plots a point for each biological replicate. That is not appropriate because the protein abundance (by plate reader) was a separate set of experiments from the RNA abundance (by qPCR), so there is no reason to pair "biorep 1" of protein data with "biorep 1" from RNA data. It's misleading as-is.

It would be more appropriate to do a star plot with point estimate and confidence intervals for each construct. Given that we already plot those for the qPCR data in `qPCR_model_coef_and_pred_vs_exp_abund.png`, why not include the protein summary statistics and make this plot as part of the [hlife_motif_pred_vs_qpcr_abund.Rmd](/DimmestP/chimera_project_manuscript/blob/master/raw_data_analysis/code/hlife_motif_pred_vs_qpcr_abund.Rmd) script?

**Comment by ewallace** [comment]
I think @DimmestP put together a nice new figure; we need to replace (current) Figure S1 with this.

**Comment by ewallace** [comment]
Ready to close, fixed by #154.
