### ISSUE TITLE
Make motif coefficient comparison plot more obviously diagonal

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#112]
Panel B of `hlife_model_multi_fig.png` should be "diagonal" in that the x and y axes are the same thing. The panel grids don't really show that, so I'll try to edit.
![image](https://user-images.githubusercontent.com/683603/114540652-b2233a00-9c4d-11eb-8c13-7703d4ec9ec6.png)

This issue spawned #111

**Comment by ewallace** [comment]
@DimmestP apologies, I failed to checkout my branch for this so accidentally committed direct to master in commit 862a7c8. Please could you review the updated figure (below), can revert or adjust if there's a problem, or accept and close.

![hlife_model_multi_fig](https://user-images.githubusercontent.com/683603/114545527-fa455b00-9c53-11eb-8781-4b9c7189a90a.png)

**Comment by ewallace** [comment]
It would be easy & quick for me to add dashed diagonal lines to all the plots, if that's helpful?

**Comment by DimmestP** [comment]
Yeah, lets see what it looks like

**Comment by ewallace** [comment]
I like it! Added in commit 193ec63, merging into master and closing this issue now.

![image](https://user-images.githubusercontent.com/683603/114590411-a56c0980-9c80-11eb-9bf1-e4b69c52be15.png)
