### ISSUE TITLE
Consistent colour schemes for terminators labels on figures

### ISSUE THREAD

**Issue by jauxillos** [DimmestP/chimera_project_manuscript#119]
- Change colour scheme for the tPIRI1 motif table, tPIR1 terminator label and tPIR1 qPCR data points in figure 5A, 5B and 6A (bottom panel)
    - Hexadecimal colour codes for tPIR1 terminators
              - WT_ATHHH - #878787 
              - mod_NTHHH - #C15659 
              - mod_ANHHH - #5978BA 
              - mod_ATNHH - #4EB0B5 
              - mod_ATHNH - #D97F1D 
              - mod_ATNNN - #71519C 
              - mod_ANNNN - #968BC2 
              - mod_NTNNN - #DD76A5

- Change colour scheme for tRPS3 and tTSA1 constructs in figure 6A (top panel)
    - Hexadecimal colour codes for tRPS3 and tTSA1 terminators
              - WT - #878787 
              - mod_NNN - #000000 
              - mod_NAA - #C05558 
              - mod_NTN - #5978BA 
              - mod_HNH - #71519C 
              - mod_HTH - #C288BB 
              - mod_NGG - #7FBF74

**Comment by ewallace** [comment]
@j-aux and I discussed this on 9th June. We still need to make sure that Figure 6 (correlation of transcriptome prediction and reporter results) uses colours consistent with Figures 4 and 5. Hopefully these colours would be defined in `shared_figure_formatting.R`.
