### ISSUE TITLE
Create summary table of motifs

### ISSUE THREAD

**Issue by DimmestP** [DimmestP/chimera_project_manuscript#122]
Need to create a table showing the consensus sequence and actual chosen version for each construct.

**Comment by ewallace** [comment]
Also could include:
* source (paper)
* function/protein if known
* effect on log2 hl for both half-life datasets?

Reminder that HWNCATTWY is not verified as a Khd1 binding motif, but was associated with Khd1- bound transcripts. I.E. it is an indirect not a direct association.
