### ISSUE TITLE
Rename sections with numbers so they always display in order

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#143]
I am finding it increasingly distracting that the directory listing doesn't display in order, I'm losing a lot of time and energy finding bits.

I'll create a pull request where the various parts of the abstract are renamed in order:
```
00-abstract.Rmd
01-intro
....
```

Following [Jenny Bryan on naming things](http://www2.stat.duke.edu/~rcs46/lectures_2015/01-markdown-git/slides/naming-slides/naming-slides.pdf)

**EDIT** also removing `_chapter` from the directory names as it seems redundant.

Then ask @DimmestP to review.

**Comment by ewallace** [comment]
Update: I have tried this in new branch `number-sections-143` and the paper compiles.

However `git push` is hanging for over 15 minutes like [this stackoverflow thread](https://stackoverflow.com/questions/15843937/git-push-hangs-after-total-line).

**Comment by ewallace** [comment]
Update 2:

1. I succeeded in pushing by following the instructions [Exploring new frontiers for Git push performance](https://devblogs.microsoft.com/devops/exploring-new-frontiers-for-git-push-performance/)
```
git config --global pack.useSparse true
```

2. It turns out the problem is that one of git's internal files (maybe the patch?) is huge, like 56MB. Probably that is a consequence of renaming lots of directories, including those that contain binary .png files etc.

```
chimera_project_manuscript edwardwallace$ git push --set-upstream origin number-sections-143
Enumerating objects: 45, done.
Counting objects: 100% (45/45), done.
Delta compression using up to 4 threads
Compressing objects: 100% (43/43), done.
Writing objects: 100% (43/43), 14.67 MiB | 1.20 MiB/s, done.
Total 43 (delta 1), reused 18 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File b0385b3678052ce8551fe5bfd35310642749e3c5 is 56.51 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: 
remote: Create a pull request for 'number-sections-143' on GitHub by visiting:
remote:      https://github.com/DimmestP/chimera_project_manuscript/pull/new/number-sections-143
remote: 
To https://github.com/DimmestP/chimera_project_manuscript.git
 * [new branch]      number-sections-143 -> number-sections-143
Branch 'number-sections-143' set up to track remote branch 'number-sections-143' from 'origin'.
```

3. Now I don't know if the improvements from having better names will outweigh the irritation of dealing with this patch.

4. We should double-check that we have the whole repository backed up.

5. Screaming.

**Comment by DimmestP** [comment]
I am going to close this issue as we have decided not to go through with this structural change
