### ISSUE TITLE
Check figure captions are informative

### ISSUE THREAD

**Issue by DimmestP** [DimmestP/chimera_project_manuscript#151]

**Comment by daneckaw** [comment]
I'll take a look at figure captions and send comments by Monday.

**Comment by ewallace** [comment]
I was planning to look at these, @daneckaw where are your comments? Please share.

**Comment by DimmestP** [comment]
General comments:
1. Change „mTurq” to „mTurquoise2” in figure labels or at least in figure captions.
2. Spell out single digit numbers? e.g. „four” instead of 4. Or at least make it consistent, because I’ve seen both versions.

Figure 1.
A. Caption: typo: „termintators” to „terminators”

Figure 2.
A. Figure label: „Relative fluorescence per OD relative to tPgk1” – remove the first „relative”?
A. Caption: It’s pretty much the same as caption for fig. 1A – should there be some difference?
B. Figure label: „Fold change in RNA abundance” – change „RNA” to something like „reporter mRNA”?

Figure 3.
Title: is there something wrong with grammar?
A. I think the caption is wrong? Aren’t these measured half-lives from two datasets instead of predicted and actual?
C. Typo: „contributons” to „contributions”

Figure 4.
A. Figure label: „RPS3 mod_N terminator” – what is „mod_N”? It is not referenced anywhere in the paper.
B. There should be information somewhere in the figure or caption that it’s using mCherry reporter. 

Figure 5.
Should the motif table be part of 5A as in 4A? Now it’s part of 5B
A. Caption: „Final PIR1 construct” is not an accurate description of 5A – it’s a schematic of wild-type terminator, not construct. Something similar to 4A would work better.
B. Typo: „promoters; pPIR1” to „promoters: pPIR1”

Table S1.
„The variance explained by a linear containing …” - linear model? 

Table S2 and S3.
Typo: „occurances” to „occurrences”

Figure S1.
Caption says „left” and „right”, but figure has „A” and  „B”

**Comment by ewallace** [comment]
Thank you - I will work on these next, in branch `captions-151`
