### ISSUE TITLE
Add discussion paragraph on alt PolyA usage

### ISSUE THREAD

**Issue by DimmestP** [DimmestP/chimera_project_manuscript#152]
Active CREs occurring alongside a motif differ not only between genes but also between transcript isoforms.
Alternative splicing or polyadenylation are encoded by CREs, and then affect which CREs are present on the mature transcript.
HERE WE NEED A COUPLE OF EXAMPLES (Geisberg?) OR TO REMOVE THE PARAGRAPH.

**Comment by DimmestP** [comment]
Any new thoughts on this @ewallace

**Comment by ewallace** [comment]
I think we removed that paragraph or otherwise edited it out of existence.
