### ISSUE TITLE
Thoroughly check methods section

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#161]
We need to double-check the methods section, including disambiguating the various labware, "deepwell" or not.

@daneckaw has agreed to do this by next week (11th June). Then we should kick back over to @j-aux for another check.

**Comment by ewallace** [comment]
@daneckaw sent comments, @DimmestP will address Wednesday 16th afternoon.

**Comment by DimmestP** [comment]
@j-aux @daneckaw 

Question about the  **Construction of chimeric reporter plasmids** section of the methods.

Currently it says:
> Assembled plasmids were transformed into yeast BY4741 using lithium acetate transformation (Gietz and Woods 2002), and selected in SC-URA agar plates to isolate successful transformants.

Weronika has commented:
> A variant with DMSO as enhancer was used. It is described as one of options in the method paper, but it is not a part of the basic protocol.

Is this clearly explained in a protocol on protocols.io? Or does that need to be clarified here? 

Also there is a reference to a supplementary table that is not there. Do we have a plan for it to be created?

> DNA sequences used in this study are summarised in **Supplementary table X**.

**Comment by jauxillos** [comment]
It's in the protocols.io protocol. Perhaps we change it to:

"Assembled plasmids were transformed into yeast BY4741 using lithium acetate transformation with DMSO (Gietz and Woods 2002), and selected in SC-URA agar plates to isolate successful transformants."

Though this is already an incredible amount of detail for our methods section.

**Comment by DimmestP** [comment]
@j-aux 

Questions about the **RNA measurements: Strain growth, RNA extraction, RT-qPCR, and analysis** section of the methods.

Currently it says:
> We summarize here a detailed protocol that is available at (CITE protocols.io).

This links with issue #96, what is the plan for citing protocols? Where are they currently? Looking at the papers that protocol.io give as examples for how to cite it's very ironic as the links have gone stale...

Also, there is another reference to the supplementary data that hasn't been added. Plan of action?
> Primer sets were designed to detect the mCherry coding sequence, as well as internal reference genes RPS3, PGK1 and (plasmid marker) URA3, (see supplemental data X)

Also, are we happy to swap "24 deepwell plate" to "24-well deep well plate". And did we get them from 4titude or Starlab (as Weronika suggests)?

Finally in the second paragraph we say
> The pelleted cells were thawed and individually resuspended in 400 $\mu$l of RNA binding buffer (Zymo cat #R1013-2), then transferred to 2 ml screw cap tubes containing zirconia beads, lysed using the Precellys Evolution homogeniser then pelleted by centrifugation at 12,000g for 1.5 minutes. 

Is the amount of zirconia beads added and the programme used on the Precellys Evolution homogeniser available on protocol.io or do we need to add that here?

**Comment by DimmestP** [comment]
@j-aux

Questions about the **Design of modified 3’UTRs for testing the effects of mutated motifs** section of the methods.

What settings where used RNAfold to make the secondary structure figures?

Currently it says:
> These [motif] positions were selected based on key design criteria (SUP FIGURE/NOTE X).
Whats the plan for making the sup figure associated with this?

**Comment by DimmestP** [comment]
Other than the points raised above I have added all of @daneckaw comments to the materials and methods section in the branch weronika_method_comments

**Comment by DimmestP** [comment]
Clemence noticed that there is another supplementary table reference in the materials and methods that is actually missing. A table surmising the 3'UTRs we could have chosen as hosts for the motifs (from which we chose TSA1 and PIR1). It is referenced in **Design of modified 3'UTRs for testing the effects of mutated motifs**.

**Comment by daneckaw** [comment]
> Is the amount of zirconia beads added and the programme used on the Precellys Evolution homogeniser available on protocol.io or do we need to add that here?

Amount of zirconia beads is on protocols.io, but the Precellys programme is not (at least not in the protocol I have access to) - it is only described as "EW Yeast protocol".

**Comment by DimmestP** [comment]
I will recreate the cumulative frequency graphs for the positions of the motifs in their native 3'UTRs to send to Jamie to create the supplementary figure explaining the motifs positions based on key design criteria.

From meeting with Jamie on 19/07/21

**Comment by jauxillos** [comment]
Ok I'll add the following this week (from discussions with @DimmestP): 

- precellys protocol in the methods section and protocols.io protocol
- add a supplementary excel spreadsheet with the qPCR primers
- and a supplementary figure with 4 panels addressing the design of motif insertion sites (1 panel with cumulative frequency graph from Sam)
- modify the branch with the DNA sequences excel spreadsheet

**Comment by jauxillos** [comment]
Addressing -  precellys protocol in the methods section and protocols.io protocol

- I've added the precellys method in the protocols.io protocol here - https://www.protocols.io/view/column-based-rna-extraction-from-yeast-s-cerevisia-beetjben (in step 17). 

I don't think its necessary to go into that much detail in the paper, and instead, we can just cite the different protocols.io protocols we use in the methods section of the paper.

**Comment by ewallace** [comment]
There are 4 remaining dangling references, can we fix asap?

1. "DNA sequences used in this study are summarised in Supplementary table X."
2. "All primer sets were thoroughly validated by serial dilution and by confirming amplicon size, sequences are available in Supplementary data X."
3. "These positions were selected based on key design criteria (Supplementary Figure X)."
4. "To this end, median-length 3'UTRs were extracted  ...  (Supplementary Table X)"
