### ISSUE TITLE
Format figures 4 & 5 to focus attention on means

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#165]
In figures 4 & 5 (RT-qPCR results of motif cosntructs), @j-aux raised a concern that the mean bars are not visually important enough compared to the raw data spots.

Suggestions to address this:
- Make the figure taller to create whitespace between lines
- Make the spots smaller
- Play with the size/weight of the lines

**Comment by ewallace** [comment]
I think this is fixed?

**Comment by ewallace** [comment]
Requesting review from @j-aux and/or @DimmestP : I tried to address this. Is it good enough yet, or what changes still need to be made?

**Comment by DimmestP** [comment]
Certainly there doesn't seem to be any issues with pixelation any more. The only thing I'd like to raise is the construct names are in bold in the plots but not in the table. Also, I am not sure if the shade of grey used for WT is the same for the plot and the table.

**Comment by DimmestP** [comment]
I also think the promoter names at the top of each plot needs to be moved up slightly as the bottom of the small p is getting cut off.

**Comment by DimmestP** [comment]
I will add my changes (as discussed 6th July)

**Comment by ewallace** [comment]
@DimmestP while you're editing the figures with the promoter names at the top of each plot, including figure 1, could you also change the mTurq to mTurq2 in the facets for consistency? Or is that too much of a pain?

**Comment by ewallace** [comment]
Currently I fixed the manuscript text so it abbreviates to mTurq (not mTurq2) for consistency with the figure axes. Any change we should do consistently.

**Comment by DimmestP** [comment]
Struggling with figure 1 and 6 as they are so big and the captions so long that they expand beyond the normal page margins and  overlap with the page number. I can't make them smaller either else they become difficult to read.

**Comment by ewallace** [comment]
Figures 1 and 6 page setting is not ideal, but can we not deal with that yet? I created a separate issue #191 for it.

**Comment by DimmestP** [comment]
I have added all of Edwards comments and my own. I shall leave issue #191 open for further discussion on page formatting but will close this issue.
