### ISSUE TITLE
Consistent references to figures

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#171]
We are not consistent in citing figures. Thanks to Clémence for picking up on this.

On 4th June edition of manuscript:
• sometimes,FigX:page3-6
• sometimes ( Fig X) : Page 6– 17
• sometimes Fig. X / Supp. X (page 3-13, 17)
• sometimes Figure X (page 14 - 15)

**Comment by DimmestP** [comment]
Changed all reference to figures and tables to (Table 1), (Figure 1) or (Supplementary Figure 1). Available in branch clemence_spelling_comments.
