### ISSUE TITLE
Fix spelling errors 

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#172]
Thanks to Clémence for picking up on these, see attached pdf referring to 4th June edition of manuscript.

[tableau article - v. June 4th.pdf](https://github.com/DimmestP/chimera_project_manuscript/files/6623303/tableau.article.-.v.June.4th.pdf)

**Comment by DimmestP** [comment]
Sam will add them on Thursday 17th.

**Comment by DimmestP** [comment]
I have added all of Cléménce's edits to the manuscript or referred to them in other issue tickets if incomplete. Edits available in the branch clemence_spelling_comments
