### ISSUE TITLE
Respond to comments from Erika Szymanski

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#194]
Details on email...

**Comment by ewallace** [comment]
There's two remaining comments that I'm not sure how to respond to.

> I understand that the study is about the combinatorial effects of CREs; nevertheless, you have me wondering about non-decomposable effects of CREs in the context of different coding sequences. As I read it, using two fluorescent reporter genes as CDS is a control against effects specific to any one gene. Is that right? If not, maybe it’s worth foregrounding the (non-)relevance of CDS?

> “Interestingly, motifs appear to have consistently greater than predicted effects on mRNA abundance when their host terminator is paired with its native promoter.” Indeed! Do you have thoughts on why that might be? I’m curious to know whether there are reasons to think that it might (or might not) have something to do with physical interactions between two ends of a sequence (or the proteins bound to them).

@j-aux @DimmestP any thoughts?

**Comment by DimmestP** [comment]
Sam will suggest amendments to introduction by Friday 30th July.

**Comment by ewallace** [comment]
Let's check what we say about interactions of other CREs with CDS choice and figure out what needs clarifying.

**Comment by DimmestP** [comment]
In terms of talking about CREs and CDS we do say the following in the results section:

> The interaction of coding sequence
and terminator is seen most clearly for tPAB1. tPAB1 is consistently the most highly expressed terminator in
mTurq constructs, but is more variable in mCherry constructs.

Then we make a general statement in the discussion.

> However,
our observations of 1.5 fold change in the relative effect of terminators depending on coding sequence and
promoter choice highlight the quantitative limitations of the assumption of composability.

I just want to make sure I understand Erika's first comment correctly. We are not "using two fluorescent reporter genes as CDS as a control against effects specific to any one gene". I feel the use of two CDS was more than just a control, we wanted to highlight CRE dependence on CDS, not remove it from the equation. Therefore, we need to foreground the relevance of CDS. Do you agree?
