### ISSUE TITLE
Twitter thread for preprint

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#206]
New preprint, with co-first authors @jamieauxillos and @youvegotmyname.
Probing 3′UTRs as modular regulators of gene expression
https://doi.org/10.1101/2021.08.12.455418
1/

What we did: test the effects of different 3'UTRs on gene expression on gene expression *in combination with multiple different promoters* in yeast.
All in the YeastFab modular cloning system from @caiyizhi lab.
2/ 
![chimera_swaps_overview](https://user-images.githubusercontent.com/683603/129369671-0570af49-4e60-4a1b-a42b-ddd021c707f1.png)

What we did next: test 3x motifs inserted in 3x 3'UTRs expressed from 3x promoters - this many combinations is unusual. Motifs chosen by statistical modeling of 2 different mRNA decay datasets, inspired by papers from @gagneurlab.
3/

What we found: whole 3'UTRs and motifs have different quantitative effects depending on all the other parts in the gene. Sometimes bigger, sometimes smaller, than simple models of independent effects of cis-regulatory elements, that we typically use to discover motifs.
4/ 
![qPCR_model_coef_and_pred_vs_exp_abund_panelA](https://user-images.githubusercontent.com/683603/129372767-883bd147-d123-488f-af1a-e4bc9da7219e.png)

Why it matters: a lot of #syntheticbiology or everyday molecular biology / motif discovery assumes cis-regulatory elements are "composable", roughly, have linear additive effects.
It matters for engineering and experimental design. Is that really true?
5/

Well, often elements are composable, sometimes they aren't, you have to test them to find out.
@srikosuri has a nice paper on composability in bacterial promoters & ribosome binding sites, we find similarly in yeast promoters & RNA decay motifs.
6/

Also, motif search or linear models that implicitly assume independent effects are probably missing a lot of important regulation. This has been known for >30years, but still the everyday tools are based on composability / independent effects.
7/

Why we really did this (whispered): to plan a large scale experiment on 3'UTR regulation, we needed to choose which promoters and UTRs to use. This "pilot experiment" grew legs and told us we'll have to use multiple promoters to really know what's going on.
8/

Thanks to co-authors Clémence Alibert, Abhishek Jain, and Weronika Danecka. Excited that project students CA & AJ in the lab contributed to a published story!
9/9

**Comment by ewallace** [comment]
Comments and corrections please!

**Comment by DimmestP** [comment]
I rather like it. My only suggestion would be to have the 2nd tweet just be about 3'UTR and promoter swaps (just because the figure in tweet 2 doesn't say anything about motifs). 

> What we did: 1) test the effects of different 3'UTRs on gene expression in combination with multiple different promoters in yeast.
All in the YeastFab modular cloning system from @caiyizhi lab.

Then introduce motif swaps in the 3rd tweet.

> What we did: 2) test the effects of motifs within 3'UTRs on gene expression with multiple different promoters in yeast.

**Comment by jauxillos** [comment]
I agree with Sam

For the 4th tweet - I also added in ‘genetic’ in the last sentence. Also, I’m not sure but why not use the #synbio instead?

4/
Why it matters: a lot of #synbio or everyday molecular biology/ motif discovery assumes cis-regulatory elements are "composable", roughly, have linear additive effects.
It matters for genetic engineering and experimental design. Is that really true?

**Comment by ewallace** [comment]
Sorry @j-aux you missed publication deadline by half an hour, even though your edits are spot on :(
