### ISSUE TITLE
Edward comments on RNA-Seq section

### ISSUE THREAD

**Issue by DimmestP** [DimmestP/chimera_project_manuscript#212]
- poly(A) site spelling used throughout
- substantial edits explaining rationale and controls
- started separate paragraph on 5PSeq

**Comment by DimmestP** [comment]
- [ ] Add QuantSeq Rev protocol reference
- [x] check number of reads on each construct
- [x] supplementary figure comparing sample correlation
- [x] compare native and construct WT poly(A) sites (for both 5PSeq and Quantseq)
- [x] reference to 5PSeq paper

**Comment by DimmestP** [comment]
- [x] selection of native genes Poly(A) site usage across samples

**Comment by DimmestP** [comment]
Do we have a link to the QuantSeq Rev protocol? @ewallace

**Comment by ewallace** [comment]
I think we just have to say "using the Quant-Seq REV kit from Lexogen (Lexogen Gmbh, Vienna Austria)." See https://doi.org/10.1016/bs.mie.2021.03.020 - it is a commercial protocol and I didn't find an academic citation for it.

**Comment by DimmestP** [comment]
Ok, Ill add that.
