### ISSUE TITLE
Go over acknowledgments

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#216]
We should acknowledge:
- WTCRF genetics core for QuantSeq sequencing
- Karolinska institute or Vicent Pelechano for 5PSeq sequencing
- Ivan Clark and Luis Montano for help with plate reader analysis @j-aux ?

**Comment by jauxillos** [comment]
Luis Montano and Peter Swain for help with the plate reader analysis. Ivan Clark and Ish (Iseabail Farquhar) helped us with the experimental set up for the plate reader experiments
