### ISSUE TITLE
Cite Nextflow

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#217]
DiTommaso2017 for nextflow:
> Di Tommaso, P., Chatzou, M., Floden, E. W., Barja, P. P., Palumbo, E., & Notredame, C. (2017). Nextflow enables reproducible computational workflows. Nature Biotechnology, 35(4), 316–319. [doi:10.1038/nbt.3820](http://www.nature.com/nbt/journal/v35/n4/full/nbt.3820.html)

I think all the rest of the software is cited?

**Comment by DimmestP** [comment]
I have added the missing citation in commit #d2a423e
