### ISSUE TITLE
Update citations to bioRxiv preprints

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#224]
Bayne et al 2020 currently cites the bioRxiv, but it shoudl really cite the updated and published paper.
We should also check any other cited preprints to see if they have been published.

https://ewallace.github.io/papers/paper/ssd1-alternative-rna-recognition

@article{10.1093/nar/gkab615,
    author = {Bayne, Rosemary A and Jayachandran, Uma and Kasprowicz, Aleksandra and Bresson, Stefan and Tollervey, David and Wallace, Edward W J and Cook, Atlanta G},
    title = "{Yeast Ssd1 is a non-enzymatic member of the RNase II family with an alternative RNA recognition site}",
    journal = {Nucleic Acids Research},
    volume = {50},
    number = {5},
    pages = {2923-2937},
    year = {2021},
    month = {07},
    abstract = "{Ssd1, a conserved fungal RNA-binding protein, is important in stress responses, cell division and virulence. Ssd1 is closely related to Dis3L2 of the RNase II family of nucleases, but lacks catalytic activity and likely suppresses translation of bound mRNAs. Previous studies identified RNA motifs enriched in Ssd1-associated transcripts, yet the sequence requirements for Ssd1 binding are not defined. Here, we identify precise binding sites of Ssd1 on RNA using in vivo cross-linking and cDNA analysis. These sites are enriched in 5′ untranslated regions of a subset of mRNAs encoding cell wall proteins. We identified a conserved bipartite motif that binds Ssd1 with high affinity in vitro. Active RNase II enzymes have a characteristic, internal RNA binding path; the Ssd1 crystal structure at 1.9 Å resolution shows that remnants of regulatory sequences block this path. Instead, RNA binding activity has relocated to a conserved patch on the surface of the protein. Structure-guided mutations of this surface prevent Ssd1 from binding RNA in vitro and phenocopy Ssd1 deletion in vivo. These studies provide a new framework for understanding the function of a pleiotropic post-transcriptional regulator of gene expression and give insights into the evolution of regulatory and binding elements in the RNase II family.}",
    issn = {0305-1048},
    doi = {10.1093/nar/gkab615},
    url = {https://doi.org/10.1093/nar/gkab615},
    eprint = {https://academic.oup.com/nar/article-pdf/50/5/2923/42919367/gkab615.pdf},
}

**Comment by DimmestP** [comment]
Fixed with commit 5c05d0300045ed2b6af16f382f4df6a059d59706
