### ISSUE TITLE
Figure S3 formatting

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#225]
Clear up formatting of Supplementary Figure S3. (histogram of Relative positions of TGTAHMNUA and HWNCAUUWY motifs in native 3’UTRs.)

- use the same theme, modified `theme_cowplot` as in [shared_figure_formatting.R](https://github.com/DimmestP/chimera_project_manuscript/blob/nar-format/raw_data_analysis/code/shared_figure_formatting.R)
- expand limits less, I think `xlim = c(0,1)`?
- Give additional line of explanation. Maybe "Histogram shows the counts of the motif occurrences in 3'UTRs relative to the total length of 3'UTR, where 0 would be starting exactly at the stop codon and 1 would be at the reported poly(A)-site. See (methods or ref to data repository) for details."

**Comment by DimmestP** [comment]
Fixed with commit 3307d34710ecc2488f26e8fc664d67c637889df5
