### ISSUE TITLE
Figure out pSRO9-mCh-tPGK1 values 

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#48]
In the current version of the analysis, some "fold changes" for pSRO9-mCh-tPGK1 and other pSRO9-mCh-txxx are below zero. That shouldn't be possible; check normalizations.

**Comment by DimmestP** [comment]
For constructs with negative fold changes their raw fluorescence values were ~0. However, once you remove autofluorescence and media contributions to the raw fluorescence you can get negative values (simply because of the minimal raw fluorescence values are dominated by noise)

**Comment by DimmestP** [comment]
Should I just replace negative values with 0?

**Comment by ewallace** [comment]
No, we shouldn't replace them, we should document them. It does point to a problem with omniplate or a problem with noise effects. I suggest we use `oob = scales::squish()` and y limit of zero to avoid _plotting_ anything below zero, with a note in the figure legend about excluded points and noise.

**Comment by ewallace** [comment]
Further, this gives us a principled reason why fold changes of fluorescence from pSRO9 and pCLN2 are too noisy to be informative.
