### ISSUE TITLE
Explain 3'UTR length is included in hlife prediction model?

### ISSUE THREAD

**Issue by DimmestP** [DimmestP/chimera_project_manuscript#55]
Currently the linear model used for predicting a transcript's half life with codon usage and motif frequency as predicates also includes a term for 3'UTR length. Should that be removed?

**Comment by DimmestP** [comment]
I see no reason to remove 3'UTR length from model, just make sure it is referenced in manuscript

CLOSE?

**Comment by ewallace** [comment]
Edited the issue title to reflect that we need to explain 3'UTR length is used in the model, in the manuscript. Only then close.

**Comment by ewallace** [comment]
I think this is fixed by #94 (in results section) and #102 (in methods section).

Let's check.
