### ISSUE TITLE
Cite fluorescent protein origins

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#81]
mCherry - cite [Shaner 2004](https://doi.org/10.1038/nbt1037)

@j-aux I know mCherry is used in the YeastFab 2015 paper, what should we cite for the choice of yeast codon-optimized versions of that?

mTurquoise2 - cite [Goedhart 2012](https://doi.org/10.1038/ncomms1738)
I checked that this sequence is [mTurquoise2](https://www.fpbase.org/protein/mturquoise2/), which differs from mTurquoise by an I146F substitution (search for `KLEYNYFSDN`)

Again, where is the mTurquoise2 coding sequence from?

**Comment by ewallace** [comment]
Note - I checked and these proteins have 30% amino acid identity, so that number is going in the draft.

And I added the Shaner 2004 and Goedhart 2012 references in commit 3897bc0

**Comment by jauxillos** [comment]
For the mTurquoise2 we used, it was amplified from [Lee 2015](https://pubs.acs.org/doi/10.1021/sb500366v). For the mCherry we used, it was amplified from [Guo 2015](https://academic.oup.com/nar/article/43/13/e88/2414193)

**Comment by ewallace** [comment]
Thanks! Lee 2015 doesn't say how they designed their codons or if it was synthesized/amplified, as far as I can tell. I will email the corresponding authors about that.

**Comment by ewallace** [comment]
Is the mCherry sequence the same as that used in [Sharon 2012](https://www.nature.com/articles/nbt.2205), i.e. the Segal lab dual-reporter plasmid?

**Comment by jauxillos** [comment]
Yes. [Guo 2015](https://academic.oup.com/nar/article/43/13/e88/2414193) amplified from [Sharon 2012](https://www.nature.com/articles/nbt.2205). 

They amplified from 'pAG60-TEF2-Cherry plasmid' from the [Breslow 2008](https://pubmed.ncbi.nlm.nih.gov/18622397/) paper but I haven't figured out what their mCherry is made from.

**Comment by ewallace** [comment]
Huh. Maybe that explains why the mCherry is so ridiculously GC-rich?

**Comment by ewallace** [comment]
We still need to add references to the **codon encodings** used for these to the draft.

**Comment by DimmestP** [comment]
I will compare these sequences to check where we got them from (July 6th Meeting)

**Comment by ewallace** [comment]
> They amplified from 'pAG60-TEF2-Cherry plasmid' from the [Breslow 2008](https://pubmed.ncbi.nlm.nih.gov/18622397/) paper but I haven't figured out what their mCherry is made from.

I checked the supplementary info of Breslow 2008, and it uses dTomato not mCherry. So maybe we give up on this? We use fluorescent proteins that have been used before and we cite where we got them. But we haven't even tried to control for codon usage.

**Comment by ewallace** [comment]
After discussing with @DimmestP , commit 5c64604 adds immediate references. That is good enough for me. Closing as we merge #199
