### ISSUE TITLE
FIX figure reference in discussion.Rmd

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#88]
`discussion.Rmd` lines 15/16 seem to be causing a failure of document preparation,

```
TO FIX: 
\@ref(fig:hlife-decay-model)C with their magnitudes calculated according to the data sets plotted against each other.
```

The error is:
>! Package caption Error: \caption outside float.

Let's fix this quickly so that we can compile the pdf again.

But maybe that will be fixed by Sam's discussion edits?

**Comment by ewallace** [comment]
Update: maybe that is not causing the problem.

@DimmestP is yours compiling ok or are you getting the same error?

**Comment by DimmestP** [comment]
Apologies, its actually the new secondary structure figure in the supplementary figures. I chatted with Jamie about making them smaller but didn't remove the code which adds them to the manuscript. I have just pushed a new commit to the master branch that should solve it until a new figure is made.

**Comment by ewallace** [comment]
Great - it is nice to keep problems like that away from the master branch.
