### ISSUE TITLE
Decide which references to protocols.io to use

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#96]
@j-aux made a LOT of great protocols on protocols.io for this paper

* plate reader
* transformation
* growth
* RT-qPCR (I helped with that)

Let us make a list of the ones that we want to refer to in the paper. Then we can check them over, get back in touch with the protocols.io team, and do that blogpost that we were talking about.

**Comment by jauxillos** [comment]
- There are 2x golden gate ones (one for Esp31 and another for Bsa1) that I started making for this paper but I haven't finished them and put it in the general lab protocols yet. 

- RNA extraction is another that we have on protocols.io already

**Comment by ewallace** [comment]
Great. I haven't thought through how to cite those. Thinking.

**Comment by ewallace** [comment]
We discussed this on 1st June. This needs a conversation and an action plan.

**Comment by ewallace** [comment]
I think this will be addressed by #199.
